/**
 * Example:
 *   // Insert CSS styles object generated by `css-loader` into DOM
 *   var removeCss = insertCss([[1, 'body { color: red; }']]);
 *
 *   // Remove it from the DOM
 *   removeCss();
 */
const renderedModules = [];

function getCss(styles) {
  const stylesToRender = styles.filter((module) => {
    const [moduleId] = module;

    // Check if we've already rendered a module with this ID
    if (!renderedModules.includes(moduleId)) {
      renderedModules.push(moduleId);
      return module;
    }

    return false;
  });
  stylesToRender.toString = styles.toString;

  return stylesToRender.toString();
}

module.exports = getCss;
